package com.maomkt.product.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.maomkt.product.model.ProductForm;

@DynamoDBTable(tableName="product")
public class Product {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    private String name;
    private String description;

    private Number quantity;

    private Number minimalQuantity;

    private Number unitPrice;

    public Product() {
    }

    public Product(ProductForm productForm) {
        this.name =productForm.getName();
        this.description = productForm.getDescription();
        this.quantity = productForm.getQuantity();
        this.minimalQuantity = productForm.getMinimalQuantity();
        this.unitPrice = productForm.getUnitPrice();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    public void setQuote(String description) {
        this.description = description;
    }
}
